create table if not exists public.history (
  id bigint generated by default as identity primary key,
  a numeric not null,
  operator text not null,
  b numeric not null,
  result numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists history_created_at_idx
  on public.history (created_at desc);